from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import List, Optional

@dataclass
class ServoState:
    id: int; position: int; angle: float; speed: float; load: float
    voltage: float; temperature: float; torque_enabled: bool; moving: bool

class ServoDriver(ABC):
    @abstractmethod
    def connect(self, port: Optional[str] = None) -> bool: ...
    @abstractmethod
    def disconnect(self): ...
    @abstractmethod
    def is_connected(self) -> bool: ...
    @abstractmethod
    def get_position(self, servo_id: int) -> int: ...
    @abstractmethod
    def set_position(self, servo_id: int, position: int, speed: int = 0): ...
    @abstractmethod
    def get_angle(self, servo_id: int) -> float: ...
    @abstractmethod
    def set_angle(self, servo_id: int, angle: float, speed_pct: int = 50): ...
    @abstractmethod
    def get_all_angles(self, servo_ids: List[int]) -> List[float]: ...
    @abstractmethod
    def set_all_angles(self, servo_ids: List[int], angles: List[float], speed_pct: int = 50): ...
    @abstractmethod
    def enable_torque(self, servo_id: int, enabled: bool): ...
    @abstractmethod
    def set_damping_mode(self, servo_id: int, enabled: bool, damping: int = 50): ...
    @abstractmethod
    def get_state(self, servo_id: int) -> ServoState: ...
    @abstractmethod
    def get_all_states(self, servo_ids: List[int]) -> List[ServoState]: ...
    @abstractmethod
    def ping(self, servo_id: int) -> bool: ...
    @abstractmethod
    def set_id(self, current_id: int, new_id: int) -> bool: ...
    def configure_centers(self, centers: dict): pass  # {servo_id: center_raw} — override in real driver
    def get_all_positions(self, servo_ids: List[int]) -> List[int]: ...
    def set_encoder(self, servo_id: int, encoder: int, speed_pct: int = 50): ...
    def set_all_encoders(self, servo_ids: List[int], encoders: List[int], speed_pct: int = 50): ...
